# Dependencies
highlighter:      rouge

gems:
  - jekyll-paginate
  - jekyll-feed

# Permalinks
permalink:              /blog/:categories/:title/
# permalink:            blog/:categories/:year/:month/:day/:title/

# Setup
title:            'VISHNU KT'
name:             'VISHNU KT'
#tagline:          ''
description:      'Software Engineer'
#url:              http://vishnukt.github.io/
baseurl:
blogurl:          /blog/

# Assets
images:         '/img'
pdfs:           '/pdf'

author:
  name:           'VISHNU KT'
  url:            vishnukt.github.io
  email:          'kt.vishnu19@gmail.com'
  github:         'https://github.com/vishnukt'
  facebook:       ''
  twitter:        ''
  googleplus:     ''
  linkedin:       'https://www.linkedin.com/in/vishnu-kt/ '

paginate:         5
paginate_path:    "/blog/page:num/"

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/vishnukt/vishnukt.github.io

# Collections
collections:
  - projects
  #- talks

# defaults:
#   -
#     scope:
#       path: ""
#       type: "projects" # a collection in your site, in plural form
#     values:
#       layout: "default"
